name: Cex
on:
  workflow_dispatch: # allow manual run
  schedule:
    - cron: '0 */4 * * *' # 4h

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: tanomin/airdrop
          ref: master
          token: ${{ secrets.REMOTE_REPO_ACCESS_TOKEN }}

      - name: i
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Thay đổi phiên bản Python theo nhu cầu
    
      - name: i
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: i
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Claim
        run: |
          python blum/claim.py